name: CI

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          python3.8 -m venv venv
          source venv/bin/activate
      - name: Run tests
        run: |
          . .venv/bin/activate
          pytest
